export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as LatestPosts } from './footer/LatestPosts'
export { default as Newsletter } from './footer/Newsletter'
export { default as SocialMedia } from './footer/SocialMedia'
export { default as Tags } from './footer/Tags'
